<div class="limitSelect">
  <? $limitList = $this->params->getLimitList(); if (count($limitList) > 1): ?>
    <form action="<?=$this->currentPath() . $this->results->getUrlQuery()->setLimit(null)?>" method="post">
      <label for="limit"><?=$this->transEsc('Results per page')?></label>
      <select id="limit" name="limit" class="jumpMenu">
        <? foreach ($limitList as $limitVal => $limitData): ?>
          <option value="<?=$this->escapeHtml($limitVal)?>"<?=$limitData['selected']?' selected="selected"':''?>><?=$this->escapeHtml($limitData['desc'])?></option>
        <? endforeach; ?>
      </select>
      <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
	  <? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form class="pull-right form-inline" style="margin:0" action="<?=$this->currentPath() . $this->results->getUrlQuery()->setSort(null)?>" method="post" name="sort">
    <label class="help-inline" for="sort_options_1"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu" onChange="document.sort.submit()">
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtml($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
    </form>
  <? endif; ?>
</div>